Update User Guide with Amos' parts
AY2324S1-CS2103T-W10-1/tp pull request #57
Opened 2023-10-04 12:50 UTC by amosting

Part of #50 .

This PR updates Amos' parts of the user guide.

2023-10-06 04:52 UTC, LHeng1 commented
Seems like the conflict is caused by using the original AB3 User Guide as the skeleton. I have made a skeletal version for our own project recently, maybe you can follow the [forking workflow](https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/gitAndGithub.html#forking-workflow) to update your local repo and re-do the task with the latest UG version, or can just solve it on GitHub itself even though it may be a bit confusing, at least for me.

**TLDR for the forking workflow: pull upstream repo to local repo -> do changes -> push to fork -> pull request**

Feel free to close this PR and create a new PR if using the forking workflow method instead!

2023-10-06 04:53 UTC, LHeng1 requested changes
Seems like the conflict is caused by using the original AB3 User Guide as the skeleton. I have made a skeletal version for our own project recently, maybe you can follow the [forking workflow](https://nus-cs2103-ay2324s1.github.io/website/se-book-adapted/chapters/gitAndGithub.html#forking-workflow) to update your local repo and re-do the task with the latest UG version, or can just solve it on GitHub itself even though it may be a bit confusing, at least for me.

TLDR for the forking workflow: pull upstream repo to local repo -> do changes -> push to fork -> pull request

Feel free to close this PR and create a new PR if using the forking workflow method instead!

2023-10-08 14:31 UTC, ravern commented
Once you have made the necessary changes, you can re-request a review from the reviewer

![image](https://github.com/AY2324S1-CS2103T-W10-1/tp/assets/22592318/0746034b-d3f9-46d5-955d-8509c291cafb)

2023-10-08 14:34 UTC, ravern requested changes
Merge conflict artefacts still present

2023-10-08 14:34 UTC, ravern commented on docs/UserGuide.md
> +### d. Adding an applicant: `add`
I don't think this should be included, these are artefacts of a merge conflict

2023-10-08 14:34 UTC, ravern commented on docs/UserGuide.md
> +>>>>>>> user-guide
This too

2023-10-08 14:34 UTC, ravern commented on docs/UserGuide.md
> +<<<<<<< HEAD
This too

2023-10-08 14:34 UTC, ravern commented on docs/UserGuide.md
> +=======
This too

2023-10-08 15:19 UTC, ylyma approved these changes

2023-10-08 15:20 UTC, ravern approved these changes
LGTM

2023-10-08 15:23 UTC, LHeng1 approved these changes
LGTM!

2023-10-08 15:24 UTC, merged