Add compare command
AY2324S1-CS2103T-W10-1/tp pull request #77
Opened 2023-10-20 03:53 UTC by LHeng1

This PR adds the minimal requirements for a `compare` command between two applicants, as mentioned in #25.

Further improvements should be done on the UI components for a better view of attributes.

2023-10-20 07:40 UTC, ravern requested changes
Sorry have to request changes, mainly for the `Comparable`, the rest are just nits.

2023-10-20 07:40 UTC, ravern commented on src/main/java/seedu/address/logic/commands/CompareCommand.java
> +    private String compareMessage;
Why does `compareMessage` need to be a instance variable here instead of just a local variable?

2023-10-20 07:40 UTC, ravern commented on src/main/java/seedu/address/model/person/Gpa.java
> +
IMO here it's better to implement the `Comparable` interface from Java

https://www.geeksforgeeks.org/comparable-interface-in-java-with-examples/

2023-10-20 07:40 UTC, ravern commented on src/main/java/seedu/address/ui/PersonCard.java
> +            img = notBookmarked;
I think the better solution here is to make them `static final` rather than making them camelCased.

2023-10-20 09:31 UTC, LHeng1 commented on src/main/java/seedu/address/model/person/Gpa.java
> +
Thanks, it's indeed a good idea to implement the Comparable interface for the Gpa class to make it more intuitive and when comparing instances of Gpa.

2023-10-20 09:33 UTC, LHeng1 commented on src/main/java/seedu/address/ui/PersonCard.java
> +            img = notBookmarked;
Right, thanks for the catch! I was going through checkstyle errors without realizing the context.

2023-10-21 09:28 UTC, ravern approved these changes
LGTM

2023-10-21 11:33 UTC, merged