Edit UG
AY2324S1-CS2103T-W10-1/tp pull request #89
Opened 2023-10-25 09:44 UTC by amosting

Added:
- Description of UI
- Delete feature description

Reformat:
- Feature descriptions

2023-10-26 14:16 UTC, LHeng1 requested changes
Overall LGTM, just some very small nits to fix.

2023-10-26 14:16 UTC, LHeng1 commented on docs/UserGuide.md
Can maybe add a brief description of c/COMMENT as well? For uniformity.

2023-10-26 14:16 UTC, LHeng1 commented on docs/UserGuide.md
> +        - Comment: `None`
Using ` ` seems to suggest that it is code, and doesn't feel consistent with the other fields. Maybe a simple dash would be better?

2023-10-26 14:16 UTC, LHeng1 commented on docs/UserGuide.md
>          - Student number:
Missed out the student number.

2023-10-31 12:59 UTC, ravern commented
Hey @amosting, how's this going?

2023-11-01 15:48 UTC, LHeng1 requested changes
Sorry, just a final nit and it should be fine!

2023-11-01 15:48 UTC, LHeng1 commented on docs/UserGuide.md
> +>>>>>>> 7ae7963ee74c8b190ecb6d659807beed8c4955cd
This seems to be a duplicate line with the conflict message still showing.

2023-11-02 08:17 UTC, LHeng1 approved these changes
LGTM!

2023-11-02 10:27 UTC, merged